### PR TITLE
Building GUI on Windows 64 bits

### PR DESCRIPTION
**Pull request by ghost**
Hi guys!
I was able to build the GUI on Windows 64 bits with Visual Studio 2015 and result looks great.
This is my makefile and instructions for building. I also had to do some modifications in order to fix some compile errors with msvc and issues. 

I hope you find this helpful.

### CODE REVIEW

**Comment by xCoreDev** [comment]
Hi @vcashFan !
Thanks for the pull req. Let's test !

**Comment by xCoreDev** [comment]
So far so good ;) Thanks for your help !
Please jump on Slack or Freenode if you get a chance.
Regarding your README, the legacy_stdio_definitions.lib & _iob issue is due to the link w/ the 
[slproweb.com](https://slproweb.com/products/Win32OpenSSL.html) static libs (built w/ VS2013), as there's now different stdin, stderr, & stdout defines in VS2015, best is to use the VS2015 ones. Check the prebuilt libs from: [http://www.npcglib.org/~stathis/blog/precompiled-openssl/](http://www.npcglib.org/~stathis/blog/precompiled-openssl/) or build them (thanks rudolsen for the link).
I will edit the https://github.com/openvcash/vcash/tree/master/platforms/windows README about OpenSSL / VS2015, and push the VS2015 .sln once ready.
Regarding the merge, I will check that tomorrow once back on Debian with a good coffee.
Have a good day/n8 !

**Comment by ghost** [comment]
Thanks for that information regarding fixing legacy problems. I've been doing some more improvements to the GUI. All of them are in commits above but we need some testing in order to check everything is stable. I'm going on holidays so won't be coding.

**Comment by xCoreDev** [comment]
I rebased your branch in the dev branch (https://github.com/openvcash/wxVcashGUI/tree/dev) , so I'm closing this merge req.
Yes, we will have soon more testers to get feedbacks.
Have a nice holidays !

**Pull request closed without merging**
